# Generated by Django 2.0 on 2018-03-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GruUsers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gruser',
            name='last_login',
        ),
    ]
